schema: https://countries.trevorblades.com/
documents:
  - ./src/**/*.graphql
extensions:
  codegen:
    emitLegacyCommonJSImports: false
    generates:
      ./src/generated/types.ts:
        plugins:
          - typescript
          - typescript-operations
      ./src/:
        preset: near-operation-file
        presetConfig:
          extension: .generated.ts
          baseTypesPath: generated/types.ts
        plugins:
          - typescript-operations
          - typed-document-node
